### ISSUE TITLE
Parsed synchronizing literal fails to emit `literal` event

### ISSUE THREAD

**Issue by drauschenbach** [hashmail/imap-parser#3]
This new test for `test/index.js` describes the problem:

```javascript
describe('events', function () {
  it('emits a literal event after a synchronizing literal is received', function (done) {
    var lp = new Parser()
    lp.on('literal', function () {
      done()
    })
    lp.end('TAG1 {16}\r\n')
  })
```

Current output:

```bash
$ npm test

  ...
  events
    1) emits a literal event after a synchronizing literal is received

  ✖ 1 of 18 tests failed:

  1) events emits a literal event after a synchronizing literal is received:
     Error: timeout of 2000ms exceeded
      at null.<anonymous> (/Users/davidr/workspaces/openimap/imap-parser/node_modules/mocha/lib/runnable.js:167:14)
      at Timer.listOnTimeout (timers.js:119:15)
```

**Comment by drauschenbach** [comment]
https://github.com/hashmail/imap-parser/pull/4
